import type { Metadata } from "next";
import { Noto_Sans_New_Tai_Lue } from "next/font/google";
import "./globals.css";
import PrimaryTopNav from "@/components/atoms/Navigations/PrimaryTopNav/PrimaryTopNav";
import BottomNav from "@/components/atoms/Navigations/BottomNav/BottomNav";
import StoreProvider from "@/components/wrappers/StoreProvider";
import AuthModalWrapper from "@/components/molecules/Home/HomeSections/Wrappers/AuthModalWrapper";
import { Suspense } from "react";
import ToastContainerComponent from "@/components/atoms/toast-container/ToastContainer";
import FooterWrapper from "@/components/atoms/Footer/FooterWrapper";

const notoSansNewTaiLue = Noto_Sans_New_Tai_Lue({
  variable: "--font-noto-sans-new-tai-lue",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSansNewTaiLue.variable} antalized`}>
        <StoreProvider>
          <PrimaryTopNav />
          {children}
          <BottomNav />
          <FooterWrapper />
          <Suspense>
            <AuthModalWrapper />
          </Suspense>
          <ToastContainerComponent />
        </StoreProvider>
      </body>
    </html>
  );
}
