import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import PrimaryTopNav from "@/components/atoms/Navigations/PrimaryTopNav/PrimaryTopNav";
import BottomNav from "@/components/atoms/Navigations/BottomNav/BottomNav";
import StoreProvider from "@/components/wrappers/StoreProvider";
import FooterMain from "@/components/atoms/Footer/FooterMain";
import AuthModalWrapper from "@/components/molecules/Home/HomeSections/Wrappers/AuthModalWrapper";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <PrimaryTopNav />
          {children}
          <BottomNav />
          <FooterMain />
          <Suspense>
            <AuthModalWrapper />
          </Suspense>
        </StoreProvider>
      </body>
    </html>
  );
}
